baseurl = "http://www.rjsdatascience.com"
languageCode = "en-us"
title = "RJS Data Science"
theme = "hugo-lithium-theme"
googleAnalytics = "88844885"
disqusShortname = "randomjohn"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About RJS Data Science"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Blogroll"
    url = "/content/blogroll/"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/randomjohn"
    weight = 5
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rjsdatascience"
    weight = 6

[params]
    description = "RJS Data Science -- statistics and data science professional with 15+ years experience"
    subtitle = "RJS Data Science"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

